"""Maintain the link that makes IDA discover the Memloader loader.

IDA only scans its ``loaders/`` directories for loader modules. The plugin links
``$IDAUSR/loaders/memloader_vt_loader.py`` to the loader entry file under ``loaders/``
in the plugin root. Symbolic links are preferred because they name the plugin they
belong to; on Windows without symlink permission a hard link is made instead.

Earlier versions also installed a ZIP and a URL loader. Their links are removed here,
so upgrading retires them rather than leaving loaders IDA would still offer.
"""

import logging
import os
from collections.abc import Sequence
from enum import Enum
from pathlib import Path

logger = logging.getLogger(__name__)

LINK_PREFIX = "memloader_"
LINK_NAME = f"{LINK_PREFIX}vt_loader.py"
ENTRY_MARKER = '"""IDA loader entry for Memloader'
LEGACY_STUB_MARKER = "# Generated by the Memloader plugin."


class LinkKind(Enum):
    SYMLINK = "symlink"
    HARDLINK = "hardlink"


DEFAULT_LINK_KINDS: tuple[LinkKind, ...] = (
    (LinkKind.SYMLINK, LinkKind.HARDLINK) if os.name == "nt" else (LinkKind.SYMLINK,)
)


def get_link_target(plugin_root: Path) -> Path:
    return plugin_root.resolve() / "loaders" / LINK_NAME


def is_current_link(path: Path, target: Path) -> bool:
    """True when ``path`` is a symlink to ``target`` or a hard link of it."""
    if path.is_symlink():
        return Path(os.readlink(path)) == target
    try:
        return path.is_file() and os.path.samefile(path, target)
    except OSError:
        return False


def is_memloader_link(path: Path, plugin_root: Path) -> bool:
    """True for a ``memloader_*.py`` symlink into ``plugin_root`` or a hard link of its loader."""
    if not path.name.startswith(LINK_PREFIX) or path.suffix != ".py":
        return False
    if path.is_symlink():
        return Path(os.readlink(path)).is_relative_to(plugin_root.resolve())
    return is_current_link(path, get_link_target(plugin_root))


def is_memloader_file(path: Path) -> bool:
    """True for a regular file holding a Memloader loader entry or a stub from an earlier version.

    A hard link whose target was replaced by a plugin upgrade keeps the old entry file
    content, so the first line identifies it as ours.
    """
    if path.is_symlink() or not path.is_file() or not path.name.startswith(LINK_PREFIX):
        return False
    try:
        with path.open("r", encoding="utf-8") as f:
            first = f.readline()
    except OSError:
        return False
    return first.startswith((ENTRY_MARKER, LEGACY_STUB_MARKER))


def create_link(path: Path, target: Path, kinds: Sequence[LinkKind]) -> LinkKind:
    """Link ``path`` to ``target`` with the first kind in ``kinds`` that the system permits.

    Raises:
        OSError: no kind could be created; the last error is raised.
    """
    error: OSError | None = None
    for kind in kinds:
        try:
            if kind is LinkKind.SYMLINK:
                path.symlink_to(target)
            else:
                os.link(target, path)
            return kind
        except OSError as e:
            logger.info("cannot create %s %s -> %s: %s", kind.value, path, target, e)
            error = e
    assert error is not None
    raise error


def remove_retired_links(loaders_dir: Path, plugin_root: Path) -> list[Path]:
    """Delete Memloader links other than the current one, and return the removed paths.

    This covers the ZIP and URL loaders that earlier versions installed, links left
    behind by a moved plugin root, and dangling ``memloader_*.py`` symlinks. Files
    that are not ours are left alone.
    """
    removed = []
    for path in loaders_dir.glob(f"{LINK_PREFIX}*.py"):
        if path.name == LINK_NAME:
            continue
        dangling = path.is_symlink() and not path.exists()
        if dangling or is_memloader_link(path, plugin_root) or is_memloader_file(path):
            logger.info("removing retired loader link %s", path)
            path.unlink()
            removed.append(path)
    return removed


def install_loader_links(
    loaders_dir: Path, plugin_root: Path, kinds: Sequence[LinkKind] = DEFAULT_LINK_KINDS
) -> Path:
    """Create the loader link in ``loaders_dir`` and remove retired Memloader links.

    A link that already points at the right target is left untouched. Returns the
    path of the loader link.

    Raises:
        OSError: the directory cannot be created or the link cannot be made.
    """
    loaders_dir.mkdir(parents=True, exist_ok=True)
    remove_retired_links(loaders_dir, plugin_root)

    target = get_link_target(plugin_root)
    path = loaders_dir / LINK_NAME
    if is_current_link(path, target):
        logger.debug("loader link %s is current", path)
        return path
    if path.is_symlink() or is_memloader_file(path):
        path.unlink()
    elif path.exists():
        raise OSError(f"not replacing {path}: it was not created by Memloader")
    kind = create_link(path, target, kinds)
    logger.info("created %s %s -> %s", kind.value, path, target)
    return path


def remove_loader_links(loaders_dir: Path, plugin_root: Path) -> list[Path]:
    """Delete every link into ``plugin_root`` from ``loaders_dir`` and return the removed paths."""
    removed = []
    for path in loaders_dir.glob(f"{LINK_PREFIX}*.py"):
        if is_memloader_link(path, plugin_root):
            path.unlink()
            removed.append(path)
    return removed
