"""Maintain the links that make IDA discover the Memloader loaders.

IDA only scans its ``loaders/`` directories for loader modules. The plugin links
``$IDAUSR/loaders/memloader_*.py`` to the loader entry files under ``loaders/`` in
the plugin root. Symbolic links are preferred because they name the plugin they
belong to; on Windows without symlink permission a hard link is made instead.
"""

import logging
import os
from collections.abc import Sequence
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

logger = logging.getLogger(__name__)

LINK_PREFIX = "memloader_"
ENTRY_MARKER = '"""IDA loader entry for Memloader'
LEGACY_STUB_MARKER = "# Generated by the Memloader plugin."


class LinkKind(Enum):
    SYMLINK = "symlink"
    HARDLINK = "hardlink"


DEFAULT_LINK_KINDS: tuple[LinkKind, ...] = (
    (LinkKind.SYMLINK, LinkKind.HARDLINK) if os.name == "nt" else (LinkKind.SYMLINK,)
)


@dataclass(frozen=True)
class LoaderLink:
    name: str

    @property
    def filename(self) -> str:
        return f"{LINK_PREFIX}{self.name}.py"


LINKS = (
    LoaderLink("zip_loader"),
    LoaderLink("url_loader"),
    LoaderLink("vt_loader"),
)


def get_link_target(plugin_root: Path, link: LoaderLink) -> Path:
    return plugin_root.resolve() / "loaders" / link.filename


def is_current_link(path: Path, target: Path) -> bool:
    """True when ``path`` is a symlink to ``target`` or a hard link of it."""
    if path.is_symlink():
        return Path(os.readlink(path)) == target
    try:
        return path.is_file() and os.path.samefile(path, target)
    except OSError:
        return False


def is_memloader_link(path: Path, plugin_root: Path) -> bool:
    """True for a ``memloader_*.py`` symlink into ``plugin_root`` or a hard link of one of its loaders."""
    if not path.name.startswith(LINK_PREFIX) or path.suffix != ".py":
        return False
    if path.is_symlink():
        return Path(os.readlink(path)).is_relative_to(plugin_root.resolve())
    return any(
        is_current_link(path, get_link_target(plugin_root, link)) for link in LINKS
    )


def is_dangling_memloader_link(path: Path) -> bool:
    return (
        path.is_symlink()
        and path.name.startswith(LINK_PREFIX)
        and path.suffix == ".py"
        and not path.exists()
    )


def is_memloader_file(path: Path) -> bool:
    """True for a regular file that holds a Memloader loader entry or a stub from an earlier version.

    A hard link whose target was replaced by a plugin upgrade keeps the old entry
    file content, so the first line identifies it as ours.
    """
    if path.is_symlink() or not path.is_file() or not path.name.startswith(LINK_PREFIX):
        return False
    try:
        with path.open("r", encoding="utf-8") as f:
            first = f.readline()
    except OSError:
        return False
    return first.startswith((ENTRY_MARKER, LEGACY_STUB_MARKER))


def create_link(path: Path, target: Path, kinds: Sequence[LinkKind]) -> LinkKind:
    """Link ``path`` to ``target`` with the first kind in ``kinds`` that the system permits.

    Raises:
        OSError: no kind could be created; the last error is raised.
    """
    error: OSError | None = None
    for kind in kinds:
        try:
            if kind is LinkKind.SYMLINK:
                path.symlink_to(target)
            else:
                os.link(target, path)
            return kind
        except OSError as e:
            logger.info("cannot create %s %s -> %s: %s", kind.value, path, target, e)
            error = e
    assert error is not None
    raise error


def install_loader_links(
    loaders_dir: Path, plugin_root: Path, kinds: Sequence[LinkKind] = DEFAULT_LINK_KINDS
) -> list[Path]:
    """Create the loader links in ``loaders_dir`` and remove stale Memloader links.

    Links that already point at the right target are left untouched. Links into
    ``plugin_root`` that are no longer expected, dangling ``memloader_*.py`` links,
    and generated stub files from earlier versions are removed. Other files are
    never modified.

    Raises:
        OSError: the directory cannot be created or a link cannot be made.
    """
    loaders_dir.mkdir(parents=True, exist_ok=True)
    wanted = {link.filename: get_link_target(plugin_root, link) for link in LINKS}

    for path in loaders_dir.glob(f"{LINK_PREFIX}*.py"):
        if path.name in wanted:
            continue
        if is_memloader_link(path, plugin_root) or is_dangling_memloader_link(path):
            logger.info("removing stale loader link %s", path)
            path.unlink()

    created = []
    for filename, target in wanted.items():
        path = loaders_dir / filename
        if is_current_link(path, target):
            logger.debug("loader link %s is current", path)
        else:
            if path.is_symlink() or is_memloader_file(path):
                path.unlink()
            elif path.exists():
                logger.warning(
                    "not replacing %s: it was not created by Memloader", path
                )
                continue
            kind = create_link(path, target, kinds)
            logger.info("created %s %s -> %s", kind.value, path, target)
        created.append(path)
    return created


def remove_loader_links(loaders_dir: Path, plugin_root: Path) -> list[Path]:
    """Delete every link into ``plugin_root`` from ``loaders_dir`` and return the removed paths."""
    removed = []
    for path in loaders_dir.glob(f"{LINK_PREFIX}*.py"):
        if is_memloader_link(path, plugin_root):
            path.unlink()
            removed.append(path)
    return removed
