import os
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest
from conftest import PLUGIN_ROOT, create_idausr
from pe import build_minimal_pe
from vtloader.install import (
    LINK_NAME,
    get_link_target,
    install_loader_links,
)

RETIRED = (
    "memloader_zip_loader.py",
    "memloader_url_loader.py",
    "memloader_vt_loader.py",
)


def make_plugin_root(tmp_path: Path) -> Path:
    """A plugin root holding a loader entry file, without the rest of the plugin."""
    root = tmp_path / "plugin"
    (root / "loaders").mkdir(parents=True)
    get_link_target(root).write_text('"""IDA loader entry for vtloader TEST."""\n')
    return root


def test_install_creates_a_symlink_into_plugin_root(tmp_path):
    loaders = tmp_path / "loaders"
    plugin_root = make_plugin_root(tmp_path)

    path = install_loader_links(loaders, plugin_root)

    assert path.name == LINK_NAME
    assert path.is_symlink()
    assert path.resolve() == get_link_target(plugin_root).resolve()


def test_install_is_idempotent_and_retargets_when_root_moves(tmp_path):
    loaders = tmp_path / "loaders"
    root_a = make_plugin_root(tmp_path / "a")
    root_b = make_plugin_root(tmp_path / "b")

    path = install_loader_links(loaders, root_a)
    inode = path.lstat().st_ino
    assert install_loader_links(loaders, root_a).lstat().st_ino == inode

    install_loader_links(loaders, root_b)
    assert path.resolve() == get_link_target(root_b).resolve()


def test_install_retires_the_memloader_links(tmp_path):
    """Upgrading from Memloader must not leave its three loaders behind."""
    loaders = tmp_path / "loaders"
    loaders.mkdir()
    plugin_root = make_plugin_root(tmp_path)
    for name in RETIRED:
        (loaders / name).symlink_to(plugin_root / "loaders" / name)
    (loaders / "memloader_stub_loader.py").write_text(
        "# Generated by the Memloader plugin.\n"
    )

    install_loader_links(loaders, plugin_root)

    assert sorted(p.name for p in loaders.iterdir()) == [LINK_NAME]


def test_install_upgrades_a_legacy_hard_link_to_a_symlink(tmp_path):
    """A hard link left by pre-1.1 vtloader on Windows is replaced with a symlink."""
    loaders = tmp_path / "loaders"
    loaders.mkdir()
    plugin_root = make_plugin_root(tmp_path)
    target = get_link_target(plugin_root)
    os.link(target, loaders / LINK_NAME)
    assert not (loaders / LINK_NAME).is_symlink()

    install_loader_links(loaders, plugin_root)

    assert (loaders / LINK_NAME).is_symlink()
    assert (loaders / LINK_NAME).resolve() == target.resolve()


def test_install_replaces_an_orphaned_entry_file_at_the_link_name(tmp_path):
    loaders = tmp_path / "loaders"
    loaders.mkdir()
    old = loaders / LINK_NAME
    old.write_text('"""IDA loader entry for vtloader, left by an upgrade."""\n')
    plugin_root = make_plugin_root(tmp_path)

    install_loader_links(loaders, plugin_root)

    assert old.is_symlink()
    assert old.resolve() == get_link_target(plugin_root).resolve()


def test_install_removes_dangling_links_but_leaves_foreign_files(tmp_path):
    loaders = tmp_path / "loaders"
    loaders.mkdir()
    plugin_root = make_plugin_root(tmp_path)
    dangling = loaders / "vtloader_removed_loader.py"
    dangling.symlink_to(tmp_path / "elsewhere" / "vtloader_removed_loader.py")
    foreign_target = tmp_path / "mine.py"
    foreign_target.write_text("x = 1\n")
    foreign_link = loaders / "vtloader_mine.py"
    foreign_link.symlink_to(foreign_target)
    foreign_file = loaders / "vtloader_other.py"
    foreign_file.write_text("def accept_file(li, f):\n    return 0\n")

    install_loader_links(loaders, plugin_root)

    assert not dangling.is_symlink()
    assert foreign_link.is_symlink()
    assert foreign_file.is_file()
    assert (loaders / LINK_NAME).is_symlink()


def test_install_refuses_to_replace_a_file_it_did_not_create(tmp_path):
    loaders = tmp_path / "loaders"
    loaders.mkdir()
    (loaders / LINK_NAME).write_text("# someone else's loader\n")

    with pytest.raises(OSError, match="not created by vtloader"):
        install_loader_links(loaders, make_plugin_root(tmp_path))


OPEN_SCRIPT = textwrap.dedent(
    """
    import sys
    import idapro, ida_ida, ida_registry
    ida_registry.reg_write_int("EULA 90", 1)
    idapro.enable_console_messages(True)
    assert idapro.open_database(sys.argv[1], True, sys.argv[2]) == 0
    print("filetype", ida_ida.inf_get_filetype())
    idapro.close_database(False)
    """
)


def run_idalib(
    cwd: Path, idausr: Path, input_file: Path, args: str
) -> subprocess.CompletedProcess:
    """Open ``input_file`` in a separate idalib process that sees nothing but ``idausr``."""
    env = {k: v for k, v in os.environ.items() if k != "PYTHONPATH"}
    env["IDAUSR"] = str(idausr)
    return subprocess.run(
        [sys.executable, "-c", OPEN_SCRIPT, str(input_file), args],
        cwd=cwd,
        env=env,
        capture_output=True,
        text=True,
    )


def test_plugin_alone_makes_ida_find_the_loader(ida, tmp_path):
    """The plugin installs its symlink at IDA startup, so the loader is selectable by name."""
    sample = tmp_path / "sample.exe"
    sample.write_bytes(build_minimal_pe())

    result = run_idalib(tmp_path, Path(os.environ["IDAUSR"]), sample, "-Ovtloader:")

    assert result.returncode == 0, result.stderr
    assert "filetype 11" in result.stdout
    assert (Path(os.environ["IDAUSR"]) / "loaders" / LINK_NAME).is_symlink()
