"""Maintain the symlink that makes IDA discover the loader.

IDA only scans its ``loaders/`` directories for loader modules. The plugin symlinks
``$IDAUSR/loaders/vtloader_loader.py`` to the loader entry file under ``loaders/`` in
the plugin root.

This plugin was called Memloader up to version 1.1 and installed three loaders: ZIP,
URL and VirusTotal. Their links are recognised here too, so that upgrading retires
them rather than leaving loaders IDA would still offer.
"""

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

LINK_PREFIX = "vtloader_"
LINK_NAME = f"{LINK_PREFIX}loader.py"

LEGACY_LINK_PREFIX = "memloader_"
LEGACY_MARKERS = (
    '"""IDA loader entry for Memloader',
    "# Generated by the Memloader plugin.",
)


def get_link_target(plugin_root: Path) -> Path:
    return plugin_root.resolve() / "loaders" / LINK_NAME


def has_loader_name(path: Path) -> bool:
    """True for a filename this plugin or its Memloader predecessor would have installed."""
    return path.suffix == ".py" and path.name.startswith(
        (LINK_PREFIX, LEGACY_LINK_PREFIX)
    )


def is_current_link(path: Path, target: Path) -> bool:
    """True when ``path`` is a symlink to ``target``."""
    # resolve() rather than raw readlink: on Windows, readlink returns
    # extended-length paths (\\?\…) that do not compare equal to regular ones.
    return path.is_symlink() and path.resolve() == target.resolve()


def is_our_link(path: Path, plugin_root: Path) -> bool:
    """True for a loader-named symlink into ``plugin_root``."""
    if not has_loader_name(path):
        return False
    if path.is_symlink():
        return path.resolve().is_relative_to(plugin_root.resolve())
    return False


def is_memloader_stub(path: Path) -> bool:
    """True for a regular file holding a Memloader loader entry or generated stub."""
    if path.is_symlink() or not path.is_file() or not has_loader_name(path):
        return False
    try:
        with path.open("r", encoding="utf-8") as f:
            first = f.readline()
    except OSError:
        return False
    return first.startswith(LEGACY_MARKERS)


def remove_retired_links(loaders_dir: Path, plugin_root: Path) -> None:
    """Delete our loader links in ``loaders_dir`` other than the current one.

    This covers the ZIP and URL loaders that Memloader installed, links left behind by
    a moved plugin root, dangling links, and generated stub files from Memloader. A
    live link into some other plugin's directory is left alone, as is any file that is
    not ours.
    """
    for prefix in (LINK_PREFIX, LEGACY_LINK_PREFIX):
        for path in loaders_dir.glob(f"{prefix}*.py"):
            if path.name == LINK_NAME:
                continue
            dangling = path.is_symlink() and not path.exists()
            if dangling or is_our_link(path, plugin_root) or is_memloader_stub(path):
                logger.info("removing retired loader link %s", path)
                path.unlink()


def install_loader_links(loaders_dir: Path, plugin_root: Path) -> Path:
    """Create the loader symlink in ``loaders_dir`` and remove retired links.

    A symlink that already points at the right target is left untouched. Returns the
    path of the loader link.

    Raises:
        OSError: the directory cannot be created or the symlink cannot be made.
    """
    loaders_dir.mkdir(parents=True, exist_ok=True)
    remove_retired_links(loaders_dir, plugin_root)

    target = get_link_target(plugin_root)
    path = loaders_dir / LINK_NAME
    if is_current_link(path, target):
        logger.debug("loader link %s is current", path)
        return path
    if path.is_symlink() or is_memloader_stub(path):
        path.unlink()
    elif path.exists():
        raise OSError(f"not replacing {path}: it was not created by vtloader")
    path.symlink_to(target)
    logger.info("created symlink %s -> %s", path, target)
    return path
